
project_id = "rihcwyknbdkmtqafizji"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5173"

[realtime]
enabled = true

[functions.send-invitation-email]
verify_jwt = true
