
project_id = "rihcwyknbdkmtqafizji"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[functions]
[functions.check_onboarding_status]
verify_jwt = true
[functions.update_organization_settings]
verify_jwt = true
[functions.delete-user-account]
verify_jwt = true
