
import { useState, useEffect } from "react";
import { useAccounting } from "@/modules/accounting";
import { Transaction, Account } from "@/modules/accounting/types";
import { useToast } from "@/hooks/use-toast";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Calendar } from 'lucide-react';
import { z } from "zod";
import { useForm, useFieldArray } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { CalendarIcon } from "lucide-react";
import { format } from "date-fns";
import { Calendar as CalendarComponent } from "@/components/ui/calendar";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Badge } from "@/components/ui/badge";
import { X, Plus } from "lucide-react";

interface NewTransactionDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onTransactionCreated: (transaction: Transaction) => void;
}

const transactionLineSchema = z.object({
  accountId: z.string().min(1, "Account is required"),
  description: z.string().optional(),
  debitAmount: z.coerce.number().min(0, "Debit must be a positive number or zero"),
  creditAmount: z.coerce.number().min(0, "Credit must be a positive number or zero"),
}).refine(data => {
  // Either debit or credit should be zero, not both have values
  return (data.debitAmount === 0 || data.creditAmount === 0);
}, {
  message: "Either debit or credit must be zero",
  path: ["debitAmount"],
});

const transactionSchema = z.object({
  date: z.date(),
  description: z.string().min(3, "Description is required"),
  referenceNumber: z.string().optional(),
  status: z.enum(["draft", "posted", "voided"]).default("draft"),
  lines: z.array(transactionLineSchema).min(2, "At least two transaction lines are required"),
}).refine(data => {
  // Check if the transaction is balanced
  const totalDebits = data.lines.reduce((sum, line) => sum + line.debitAmount, 0);
  const totalCredits = data.lines.reduce((sum, line) => sum + line.creditAmount, 0);
  return Math.abs(totalDebits - totalCredits) < 0.01; // Allow for small rounding errors
}, {
  message: "Transaction must be balanced (total debits must equal total credits)",
  path: ["lines"],
});

type TransactionFormValues = z.infer<typeof transactionSchema>;

export function NewTransactionDialog({
  open,
  onOpenChange,
  onTransactionCreated,
}: NewTransactionDialogProps) {
  const { createTransaction, getAccounts } = useAccounting();
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { toast } = useToast();

  const form = useForm<TransactionFormValues>({
    resolver: zodResolver(transactionSchema),
    defaultValues: {
      date: new Date(),
      description: "",
      referenceNumber: "",
      status: "draft",
      lines: [
        { accountId: "", description: "", debitAmount: 0, creditAmount: 0 },
        { accountId: "", description: "", debitAmount: 0, creditAmount: 0 },
      ],
    },
  });

  const { fields, append, remove } = useFieldArray({
    control: form.control,
    name: "lines",
  });

  useEffect(() => {
    fetchAccounts();
  }, []);

  const fetchAccounts = async () => {
    try {
      const fetchedAccounts = await getAccounts();
      setAccounts(fetchedAccounts.filter(account => account.isActive));
    } catch (error) {
      console.error("Error fetching accounts:", error);
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to fetch accounts",
      });
    }
  };

  const onSubmit = async (data: TransactionFormValues) => {
    setIsSubmitting(true);
    try {
      // Ensure no empty transaction lines
      const validLines = data.lines.filter(
        line => line.accountId && (line.debitAmount > 0 || line.creditAmount > 0)
      );
      
      // Generate simplified transaction object for API
      const transaction: Omit<Transaction, 'id' | 'createdAt' | 'updatedAt'> = {
        date: format(data.date, 'yyyy-MM-dd'),
        description: data.description,
        referenceNumber: data.referenceNumber || undefined,
        status: data.status,
        // Map to proper TransactionLine type with undefined values for id, createdAt, updatedAt
        // These will be filled in by the backend
        lines: validLines.map(line => ({
          id: '', // Will be ignored/generated by backend
          accountId: line.accountId,
          description: line.description || undefined,
          debitAmount: line.debitAmount,
          creditAmount: line.creditAmount,
          createdAt: '', // Will be ignored/generated by backend
          updatedAt: ''  // Will be ignored/generated by backend
        }))
      };
      
      const newTransaction = await createTransaction(transaction);
      
      if (!newTransaction) {
        throw new Error("Failed to create transaction");
      }
      
      toast({
        title: "Transaction created",
        description: "The transaction has been created successfully",
      });
      
      onTransactionCreated(newTransaction);
      onOpenChange(false);
      form.reset({
        date: new Date(),
        description: "",
        referenceNumber: "",
        status: "draft",
        lines: [
          { accountId: "", description: "", debitAmount: 0, creditAmount: 0 },
          { accountId: "", description: "", debitAmount: 0, creditAmount: 0 },
        ],
      });
    } catch (error) {
      console.error("Error creating transaction:", error);
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to create transaction",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  // Calculate transaction balance
  const calculateBalance = () => {
    const values = form.getValues();
    
    const totalDebits = values.lines.reduce(
      (sum, line) => sum + (parseFloat(line.debitAmount.toString()) || 0), 
      0
    );
    
    const totalCredits = values.lines.reduce(
      (sum, line) => sum + (parseFloat(line.creditAmount.toString()) || 0), 
      0
    );
    
    const difference = totalDebits - totalCredits;
    
    return {
      totalDebits,
      totalCredits,
      difference,
      isBalanced: Math.abs(difference) < 0.01, // Allow for small rounding errors
    };
  };

  const balance = calculateBalance();

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-3xl">
        <DialogHeader>
          <DialogTitle>Create New Transaction</DialogTitle>
          <DialogDescription>
            Enter the details for the new transaction below.
          </DialogDescription>
        </DialogHeader>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <FormField
                control={form.control}
                name="date"
                render={({ field }) => (
                  <FormItem className="flex flex-col">
                    <FormLabel>Date</FormLabel>
                    <Popover>
                      <PopoverTrigger asChild>
                        <FormControl>
                          <Button
                            variant={"outline"}
                            className={
                              "pl-3 text-left font-normal flex justify-between items-center"
                            }
                          >
                            {field.value ? (
                              format(field.value, "PPP")
                            ) : (
                              <span>Pick a date</span>
                            )}
                            <CalendarIcon className="ml-auto h-4 w-4 opacity-50" />
                          </Button>
                        </FormControl>
                      </PopoverTrigger>
                      <PopoverContent className="w-auto p-0" align="start">
                        <CalendarComponent
                          mode="single"
                          selected={field.value}
                          onSelect={field.onChange}
                          disabled={(date) =>
                            date > new Date() || date < new Date("1900-01-01")
                          }
                          initialFocus
                        />
                      </PopoverContent>
                    </Popover>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="status"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Status</FormLabel>
                    <Select
                      disabled={true} // New transactions can only be drafts
                      onValueChange={field.onChange}
                      defaultValue={field.value}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Select status" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="draft">Draft</SelectItem>
                        <SelectItem value="posted">Posted</SelectItem>
                        <SelectItem value="voided">Voided</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="referenceNumber"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Reference Number (Optional)</FormLabel>
                    <FormControl>
                      <Input placeholder="Enter reference number" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Description</FormLabel>
                  <FormControl>
                    <Textarea 
                      placeholder="Enter transaction description" 
                      className="resize-none" 
                      {...field} 
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="space-y-4">
              <div className="flex justify-between items-center">
                <div>
                  <Label>Transaction Lines</Label>
                  <p className="text-sm text-muted-foreground">
                    Add debit and credit lines to balance the transaction.
                  </p>
                </div>
                <div className="space-x-2">
                  <Badge variant={balance.isBalanced ? "default" : "destructive"}>
                    {balance.isBalanced 
                      ? "Balanced" 
                      : `Unbalanced (${balance.difference > 0 ? "Excess Debit" : "Excess Credit"}: $${Math.abs(balance.difference).toFixed(2)})`}
                  </Badge>
                </div>
              </div>

              <div className="border rounded-md p-4 space-y-4">
                <div className="grid grid-cols-12 gap-2 mb-2 text-sm font-medium">
                  <div className="col-span-4">Account</div>
                  <div className="col-span-3">Description</div>
                  <div className="col-span-2">Debit</div>
                  <div className="col-span-2">Credit</div>
                  <div className="col-span-1"></div>
                </div>
                
                {fields.map((field, index) => (
                  <div key={field.id} className="grid grid-cols-12 gap-2 items-center">
                    <div className="col-span-4">
                      <FormField
                        control={form.control}
                        name={`lines.${index}.accountId`}
                        render={({ field }) => (
                          <FormItem>
                            <FormControl>
                              <Select
                                onValueChange={field.onChange}
                                value={field.value}
                              >
                                <SelectTrigger>
                                  <SelectValue placeholder="Select account" />
                                </SelectTrigger>
                                <SelectContent>
                                  {accounts.map((account) => (
                                    <SelectItem key={account.id} value={account.id}>
                                      {account.code} - {account.name}
                                    </SelectItem>
                                  ))}
                                </SelectContent>
                              </Select>
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>
                    
                    <div className="col-span-3">
                      <FormField
                        control={form.control}
                        name={`lines.${index}.description`}
                        render={({ field }) => (
                          <FormItem>
                            <FormControl>
                              <Input placeholder="Description" {...field} />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>
                    
                    <div className="col-span-2">
                      <FormField
                        control={form.control}
                        name={`lines.${index}.debitAmount`}
                        render={({ field }) => (
                          <FormItem>
                            <FormControl>
                              <Input 
                                type="number" 
                                step="0.01" 
                                min="0" 
                                placeholder="0.00"
                                {...field}
                                onChange={(e) => {
                                  field.onChange(e);
                                  // If debit has a value, clear credit (following double-entry principle)
                                  if (parseFloat(e.target.value) > 0) {
                                    form.setValue(`lines.${index}.creditAmount`, 0);
                                  }
                                }}
                              />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>
                    
                    <div className="col-span-2">
                      <FormField
                        control={form.control}
                        name={`lines.${index}.creditAmount`}
                        render={({ field }) => (
                          <FormItem>
                            <FormControl>
                              <Input 
                                type="number" 
                                step="0.01" 
                                min="0" 
                                placeholder="0.00"
                                {...field}
                                onChange={(e) => {
                                  field.onChange(e);
                                  // If credit has a value, clear debit (following double-entry principle)
                                  if (parseFloat(e.target.value) > 0) {
                                    form.setValue(`lines.${index}.debitAmount`, 0);
                                  }
                                }}
                              />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>
                    
                    <div className="col-span-1 flex justify-center">
                      <Button
                        type="button"
                        variant="ghost"
                        size="sm"
                        className="h-8 w-8 p-0"
                        onClick={() => {
                          if (fields.length > 2) {
                            remove(index);
                          } else {
                            toast({
                              variant: "destructive",
                              title: "Minimum Lines Required",
                              description: "A transaction must have at least two lines"
                            });
                          }
                        }}
                      >
                        <X className="h-4 w-4" />
                        <span className="sr-only">Remove</span>
                      </Button>
                    </div>
                  </div>
                ))}
                
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  className="mt-2"
                  onClick={() => {
                    append({ accountId: "", description: "", debitAmount: 0, creditAmount: 0 });
                  }}
                >
                  <Plus className="mr-2 h-4 w-4" />
                  Add Line
                </Button>
              </div>
              
              <div className="flex justify-end space-x-4 text-sm">
                <div className="text-right">
                  <div>Total Debits:</div>
                  <div>Total Credits:</div>
                  <div className="font-semibold mt-1">Difference:</div>
                </div>
                <div className="text-right w-24">
                  <div>${balance.totalDebits.toFixed(2)}</div>
                  <div>${balance.totalCredits.toFixed(2)}</div>
                  <div className={`font-semibold mt-1 ${balance.isBalanced ? 'text-green-600' : 'text-red-600'}`}>
                    ${Math.abs(balance.difference).toFixed(2)}
                  </div>
                </div>
              </div>
            </div>

            <DialogFooter>
              <Button
                type="button"
                variant="outline"
                onClick={() => onOpenChange(false)}
              >
                Cancel
              </Button>
              <Button 
                type="submit" 
                disabled={isSubmitting || !balance.isBalanced}
              >
                {isSubmitting ? "Creating..." : "Create Transaction"}
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
