
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rihcwyknbdkmtqafizji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpaGN3eWtuYmRrbXRxYWZpemppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MjgzMTQsImV4cCI6MjA1OTIwNDMxNH0.yRAWlwvUzHzmkAcbbQVqVEkKPzMnA4lkzDRgR0WFRzA";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
